// <auto-generated />
using System;
using EgorSalahovSemestrovka22.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgorSalahovSemestrovka22.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520122217_AddEnrollmentsToCourse")]
    partial class AddEnrollmentsToCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseCount")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCount = 5,
                            ImagePath = "cat-1.png",
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = 2,
                            CourseCount = 5,
                            ImagePath = "cat-2.png",
                            Name = "Backend Development"
                        });
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAssignments")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCommunityAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDownloadableResources")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLifetimeAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMobileAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSubtitles")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("int");

                    b.Property<int>("LevelForStudent")
                        .HasColumnType("int");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Duration = new TimeSpan(0, 11, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-1.png",
                            InstructorId = 2,
                            LessonsCount = 13,
                            LevelForStudent = 0,
                            OldPrice = 99.99m,
                            Price = 50.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Modern React Guide Vol. 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Duration = new TimeSpan(0, 12, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-2.png",
                            InstructorId = 1,
                            LessonsCount = 14,
                            LevelForStudent = 0,
                            OldPrice = 99.99m,
                            Price = 51.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Advanced C# Patterns Vol. 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Duration = new TimeSpan(0, 13, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-3.png",
                            InstructorId = 2,
                            LessonsCount = 15,
                            LevelForStudent = 0,
                            OldPrice = 99.99m,
                            Price = 52.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Modern React Guide Vol. 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Duration = new TimeSpan(0, 14, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-4.png",
                            InstructorId = 1,
                            LessonsCount = 16,
                            LevelForStudent = 0,
                            OldPrice = 99.99m,
                            Price = 53.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Advanced C# Patterns Vol. 4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Duration = new TimeSpan(0, 15, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-5.png",
                            InstructorId = 2,
                            LessonsCount = 17,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 54.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Modern React Guide Vol. 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Duration = new TimeSpan(0, 16, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-6.png",
                            InstructorId = 1,
                            LessonsCount = 18,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 55.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Advanced C# Patterns Vol. 6"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Duration = new TimeSpan(0, 17, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-7.png",
                            InstructorId = 2,
                            LessonsCount = 19,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 56.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Modern React Guide Vol. 7"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Duration = new TimeSpan(0, 18, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-8.png",
                            InstructorId = 1,
                            LessonsCount = 20,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 57.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Advanced C# Patterns Vol. 8"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Duration = new TimeSpan(0, 19, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-9.png",
                            InstructorId = 2,
                            LessonsCount = 21,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 58.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Modern React Guide Vol. 9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Duration = new TimeSpan(0, 20, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-10.png",
                            InstructorId = 1,
                            LessonsCount = 22,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 59.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Advanced C# Patterns Vol. 10"
                        });
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Years")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Years")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarPath = "instructor-1.png",
                            Bio = "Senior Fullstack Developer",
                            DateOfBirth = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "egor@example.com",
                            FirstName = "Egor",
                            Gender = "Male",
                            LastName = "Salahov",
                            PhoneNumber = "+1234567890",
                            RegistrationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalEarnings = 1500.00m,
                            UserName = "egor_dev"
                        },
                        new
                        {
                            Id = 2,
                            AvatarPath = "instructor-2.png",
                            Bio = "UI/UX Expert",
                            DateOfBirth = new DateTime(1998, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna@example.com",
                            FirstName = "Anna",
                            Gender = "Female",
                            LastName = "Pro",
                            PhoneNumber = "+9876543210",
                            RegistrationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalEarnings = 2300.50m,
                            UserName = "anna_web"
                        });
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("bit");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "Lenina st. 1",
                            City = "Moscow",
                            Country = "Russia",
                            FirstName = "Ivan",
                            LastName = "Tester",
                            OrderDate = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            PaymentMethod = "Card",
                            State = "MSK",
                            StudentId = "021914cc-ba3c-4bf5-aa53-6fc9bb467f1a",
                            Tax = 10.00m,
                            TotalAmount = 150.00m
                        });
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Course", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Instructors.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Enrollment", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Education", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Instructors.Instructor", "Instructor")
                        .WithMany("Educations")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Experience", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Instructors.Instructor", "Instructor")
                        .WithMany("Experiences")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Lesson", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Section", "Section")
                        .WithMany("Lessons")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.CartItem", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", "Student")
                        .WithMany("CartItems")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.Order", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", "Student")
                        .WithMany("Orders")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.OrderItem", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Review", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Section", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Wishlist", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", "Student")
                        .WithMany("Wishlist")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Reviews");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Instructor", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Section", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Student", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Enrollments");

                    b.Navigation("Orders");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
