// <auto-generated />
using System;
using EgorSalahovSemestrovka22.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgorSalahovSemestrovka22.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514112214_AddStudentsSeed")]
    partial class AddStudentsSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseCount")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCount = 5,
                            ImagePath = "cat-1.png",
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = 2,
                            CourseCount = 5,
                            ImagePath = "cat-2.png",
                            Name = "Backend Development"
                        });
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAssignments")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCommunityAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDownloadableResources")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLifetimeAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMobileAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSubtitles")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("int");

                    b.Property<int>("LevelForStudent")
                        .HasColumnType("int");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Duration = new TimeSpan(0, 11, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-1.png",
                            InstructorId = 2,
                            LessonsCount = 13,
                            LevelForStudent = 0,
                            OldPrice = 99.99m,
                            Price = 50.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Modern React Guide Vol. 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Duration = new TimeSpan(0, 12, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-2.png",
                            InstructorId = 1,
                            LessonsCount = 14,
                            LevelForStudent = 0,
                            OldPrice = 99.99m,
                            Price = 51.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Advanced C# Patterns Vol. 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Duration = new TimeSpan(0, 13, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-3.png",
                            InstructorId = 2,
                            LessonsCount = 15,
                            LevelForStudent = 0,
                            OldPrice = 99.99m,
                            Price = 52.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Modern React Guide Vol. 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Duration = new TimeSpan(0, 14, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-4.png",
                            InstructorId = 1,
                            LessonsCount = 16,
                            LevelForStudent = 0,
                            OldPrice = 99.99m,
                            Price = 53.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Advanced C# Patterns Vol. 4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Duration = new TimeSpan(0, 15, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-5.png",
                            InstructorId = 2,
                            LessonsCount = 17,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 54.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Modern React Guide Vol. 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Duration = new TimeSpan(0, 16, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-6.png",
                            InstructorId = 1,
                            LessonsCount = 18,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 55.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Advanced C# Patterns Vol. 6"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Duration = new TimeSpan(0, 17, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-7.png",
                            InstructorId = 2,
                            LessonsCount = 19,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 56.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Modern React Guide Vol. 7"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Duration = new TimeSpan(0, 18, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-8.png",
                            InstructorId = 1,
                            LessonsCount = 20,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 57.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Advanced C# Patterns Vol. 8"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Duration = new TimeSpan(0, 19, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-9.png",
                            InstructorId = 2,
                            LessonsCount = 21,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 58.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Modern React Guide Vol. 9"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Duration = new TimeSpan(0, 20, 0, 0, 0),
                            FullDescription = "Detailed description of the course with modules and deep dives.",
                            HasAssignments = true,
                            HasCommunityAccess = true,
                            HasDownloadableResources = true,
                            HasLifetimeAccess = true,
                            HasMobileAccess = true,
                            HasSubtitles = true,
                            ImagePath = "course-10.png",
                            InstructorId = 1,
                            LessonsCount = 22,
                            LevelForStudent = 1,
                            OldPrice = 99.99m,
                            Price = 59.99m,
                            ShortDescription = "Learn the best practices in this comprehensive course.",
                            Title = "Advanced C# Patterns Vol. 10"
                        });
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Years")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Years")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarPath = "instructor-1.png",
                            Bio = "Senior Fullstack Developer",
                            DateOfBirth = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "egor@example.com",
                            FirstName = "Egor",
                            Gender = "Male",
                            LastName = "Salahov",
                            PhoneNumber = "+1234567890",
                            RegistrationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalEarnings = 1500.00m,
                            UserName = "egor_dev"
                        },
                        new
                        {
                            Id = 2,
                            AvatarPath = "instructor-2.png",
                            Bio = "UI/UX Expert",
                            DateOfBirth = new DateTime(1998, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna@example.com",
                            FirstName = "Anna",
                            Gender = "Female",
                            LastName = "Pro",
                            PhoneNumber = "+9876543210",
                            RegistrationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalEarnings = 2300.50m,
                            UserName = "anna_web"
                        });
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("bit");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "Lenina st. 1",
                            City = "Moscow",
                            Country = "Russia",
                            FirstName = "Ivan",
                            LastName = "Tester",
                            OrderDate = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            PaymentMethod = "Card",
                            State = "MSK",
                            StudentId = 1,
                            Tax = 10.00m,
                            TotalAmount = 150.00m
                        });
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarPath = "student-1.png",
                            Bio = "Learning C#",
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan@test.com",
                            FirstName = "Ivan",
                            Gender = "Male",
                            LastName = "Tester",
                            PhoneNumber = "+1234567890",
                            RegistrationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "ivan_test"
                        },
                        new
                        {
                            Id = 2,
                            AvatarPath = "student-2.png",
                            Bio = "Frontend enthusiast",
                            DateOfBirth = new DateTime(1999, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria@example.com",
                            FirstName = "Maria",
                            Gender = "Female",
                            LastName = "Sokolova",
                            PhoneNumber = "+1234567891",
                            RegistrationDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "maria_dev"
                        },
                        new
                        {
                            Id = 3,
                            AvatarPath = "student-3.png",
                            Bio = "Backend developer",
                            DateOfBirth = new DateTime(2001, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex@example.com",
                            FirstName = "Alexey",
                            Gender = "Male",
                            LastName = "Petrov",
                            PhoneNumber = "+1234567892",
                            RegistrationDate = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "alex_p"
                        },
                        new
                        {
                            Id = 4,
                            AvatarPath = "student-4.png",
                            Bio = "Fullstack learner",
                            DateOfBirth = new DateTime(1998, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olga@example.com",
                            FirstName = "Olga",
                            Gender = "Female",
                            LastName = "Ivanova",
                            PhoneNumber = "+1234567893",
                            RegistrationDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "olga_i"
                        },
                        new
                        {
                            Id = 5,
                            AvatarPath = "student-5.png",
                            Bio = "JavaScript fan",
                            DateOfBirth = new DateTime(2002, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dmitry@example.com",
                            FirstName = "Dmitry",
                            Gender = "Male",
                            LastName = "Kozlov",
                            PhoneNumber = "+1234567894",
                            RegistrationDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "dmitry_k"
                        },
                        new
                        {
                            Id = 6,
                            AvatarPath = "student-6.png",
                            Bio = "React developer",
                            DateOfBirth = new DateTime(1997, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elena@example.com",
                            FirstName = "Elena",
                            Gender = "Female",
                            LastName = "Smirnova",
                            PhoneNumber = "+1234567895",
                            RegistrationDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "elena_s"
                        },
                        new
                        {
                            Id = 7,
                            AvatarPath = "student-7.png",
                            Bio = "Python & C#",
                            DateOfBirth = new DateTime(2000, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sergey@example.com",
                            FirstName = "Sergey",
                            Gender = "Male",
                            LastName = "Volkov",
                            PhoneNumber = "+1234567896",
                            RegistrationDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "sergey_v"
                        },
                        new
                        {
                            Id = 8,
                            AvatarPath = "student-8.png",
                            Bio = "UI/UX designer",
                            DateOfBirth = new DateTime(2001, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna2@example.com",
                            FirstName = "Anna",
                            Gender = "Female",
                            LastName = "Kuznetsova",
                            PhoneNumber = "+1234567897",
                            RegistrationDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "anna_k"
                        },
                        new
                        {
                            Id = 9,
                            AvatarPath = "student-9.png",
                            Bio = "Game dev interested",
                            DateOfBirth = new DateTime(1999, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pavel@example.com",
                            FirstName = "Pavel",
                            Gender = "Male",
                            LastName = "Morozov",
                            PhoneNumber = "+1234567898",
                            RegistrationDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "pavel_m"
                        },
                        new
                        {
                            Id = 10,
                            AvatarPath = "student-10.png",
                            Bio = "Data Science student",
                            DateOfBirth = new DateTime(2002, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tatiana@example.com",
                            FirstName = "Tatiana",
                            Gender = "Female",
                            LastName = "Orlova",
                            PhoneNumber = "+1234567899",
                            RegistrationDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "tatiana_o"
                        },
                        new
                        {
                            Id = 11,
                            AvatarPath = "student-11.png",
                            Bio = "ASP.NET Core fan",
                            DateOfBirth = new DateTime(1998, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikolay@example.com",
                            FirstName = "Nikolay",
                            Gender = "Male",
                            LastName = "Fedorov",
                            PhoneNumber = "+1234567810",
                            RegistrationDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "nikolay_f"
                        },
                        new
                        {
                            Id = 12,
                            AvatarPath = "student-12.png",
                            Bio = "Mobile developer",
                            DateOfBirth = new DateTime(2000, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ekaterina@example.com",
                            FirstName = "Ekaterina",
                            Gender = "Female",
                            LastName = "Popova",
                            PhoneNumber = "+1234567811",
                            RegistrationDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "ekaterina_p"
                        },
                        new
                        {
                            Id = 13,
                            AvatarPath = "student-13.png",
                            Bio = "DevOps learner",
                            DateOfBirth = new DateTime(2001, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "andrey@example.com",
                            FirstName = "Andrey",
                            Gender = "Male",
                            LastName = "Sidorov",
                            PhoneNumber = "+1234567812",
                            RegistrationDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "andrey_s"
                        },
                        new
                        {
                            Id = 14,
                            AvatarPath = "student-14.png",
                            Bio = "QA Automation",
                            DateOfBirth = new DateTime(1999, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yulia@example.com",
                            FirstName = "Yulia",
                            Gender = "Female",
                            LastName = "Vasilieva",
                            PhoneNumber = "+1234567813",
                            RegistrationDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "yulia_v"
                        },
                        new
                        {
                            Id = 15,
                            AvatarPath = "student-15.png",
                            Bio = "Cloud computing",
                            DateOfBirth = new DateTime(2002, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maxim@example.com",
                            FirstName = "Maxim",
                            Gender = "Male",
                            LastName = "Belov",
                            PhoneNumber = "+1234567814",
                            RegistrationDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "maxim_b"
                        });
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Course", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Instructors.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Enrollment", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Education", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Instructors.Instructor", "Instructor")
                        .WithMany("Educations")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Experience", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Instructors.Instructor", "Instructor")
                        .WithMany("Experiences")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Lesson", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Section", "Section")
                        .WithMany("Lessons")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.CartItem", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", "Student")
                        .WithMany("CartItems")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.Order", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", "Student")
                        .WithMany("Orders")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.OrderItem", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Review", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Section", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Wishlist", b =>
                {
                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgorSalahovSemestrovka22.Models.Entities.Student", "Student")
                        .WithMany("Wishlist")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Course", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Instructors.Instructor", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Section", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("EgorSalahovSemestrovka22.Models.Entities.Student", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Enrollments");

                    b.Navigation("Orders");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
